import React, { createContext, useContext, useState, useCallback, useRef } from 'react'

/**
 * Notification Context — in-app notification system for order lifecycle events.
 *
 * Notifications are stored in-memory (React state) and are not persisted to the database.
 * They are generated by polling the orders table for changes.
 *
 * Notification shape:
 * {
 *   id: string,
 *   type: 'new_order' | 'order_update',
 *   title: string,
 *   message: string,
 *   orderId: string,
 *   read: boolean,
 *   createdAt: Date,
 * }
 */

const NotificationContext = createContext(null)

export function useNotifications() {
  const ctx = useContext(NotificationContext)
  if (!ctx) throw new Error('useNotifications must be used within NotificationProvider')
  return ctx
}

export function NotificationProvider({ children }) {
  const [notifications, setNotifications] = useState([])
  const [unreadCount, setUnreadCount] = useState(0)
  const idCounter = useRef(0)

  const addNotification = useCallback((notification) => {
    const id = `notif_${Date.now()}_${++idCounter.current}`
    const newNotif = {
      id,
      ...notification,
      read: false,
      createdAt: new Date(),
    }

    setNotifications(prev => {
      // Deduplicate: don't add if same orderId + type already exists
      const exists = prev.some(n => n.orderId === notification.orderId && n.type === notification.type)
      if (exists) return prev
      return [newNotif, ...prev].slice(0, 50) // Keep max 50
    })
    setUnreadCount(prev => prev + 1)
  }, [])

  const markAsRead = useCallback((notificationId) => {
    setNotifications(prev =>
      prev.map(n => n.id === notificationId ? { ...n, read: true } : n)
    )
    setUnreadCount(prev => Math.max(0, prev - 1))
  }, [])

  const markAllAsRead = useCallback(() => {
    setNotifications(prev => prev.map(n => ({ ...n, read: true })))
    setUnreadCount(0)
  }, [])

  const clearNotifications = useCallback(() => {
    setNotifications([])
    setUnreadCount(0)
  }, [])

  const removeNotification = useCallback((notificationId) => {
    setNotifications(prev => {
      const removed = prev.find(n => n.id === notificationId)
      if (removed && !removed.read) {
        setUnreadCount(c => Math.max(0, c - 1))
      }
      return prev.filter(n => n.id !== notificationId)
    })
  }, [])

  const value = {
    notifications,
    unreadCount,
    addNotification,
    markAsRead,
    markAllAsRead,
    clearNotifications,
    removeNotification,
  }

  return (
    <NotificationContext.Provider value={value}>
      {children}
    </NotificationContext.Provider>
  )
}
